## PyTorch Tutorial
MILA, December 2018

By Sandeep Subramanian

## 1. Introduction to the torch tensor library
### Torch's numpy equivalent with GPU support

In [1]:
import numpy as np
from __future__ import print_function

In [2]:
import torch

In [3]:
torch.__version__

'1.0.0'

### Initialize a random tensor

In [5]:
torch.Tensor(5, 3)

tensor([[ 0.0000e+00, -4.6566e-10,  0.0000e+00],
        [-4.6566e-10,  7.0065e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -4.6566e-10, -1.7340e+18]])

### From a uniform distribution

In [6]:
torch.Tensor(5, 3).uniform_(-1, 1)

tensor([[-0.7462, -0.9677, -0.9540],
        [ 0.6367, -0.7440,  0.0467],
        [ 0.3496, -0.3048,  0.0798],
        [ 0.4778, -0.3230,  0.6875],
        [ 0.9246,  0.4887,  0.7453]])

### Get it's shape

In [10]:
x = torch.Tensor(5, 3).uniform_(-1, 1)
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


### Tensor Types
source: http://pytorch.org/docs/master/tensors.html

|Data type |Tensor|
|----------|------|
|32-bit floating point|	torch.FloatTensor|
|64-bit floating point|	torch.DoubleTensor|
|16-bit floating point|	torch.HalfTensor|
|8-bit integer (unsigned)|torch.ByteTensor|
|8-bit integer (signed)|torch.CharTensor|
|16-bit integer (signed)|torch.ShortTensor|
|32-bit integer (signed)|torch.IntTensor|
|64-bit integer (signed)|torch.LongTensor|

### Creation from lists & numpy

In [12]:
z = torch.LongTensor([[1, 3], [2, 9]])
print(z.type())
# Cast to numpy ndarray
print(z.numpy().dtype)

torch.LongTensor
int64


In [13]:
# Data type inferred from numpy
print(torch.from_numpy(np.random.rand(5, 3)).type())
print(torch.from_numpy(np.random.rand(5, 3).astype(np.float32)).type())

torch.DoubleTensor
torch.FloatTensor


### Simple mathematical operations

In [16]:
x = torch.Tensor(5, 3).uniform_(-1, 1)
y = x * torch.randn(5, 3)
print(y, y.shape)

tensor([[ 0.1674,  1.2820,  0.0043],
        [ 1.8186, -0.2971, -0.1496],
        [ 0.2283, -0.1887,  0.1708],
        [-0.9892, -0.0125,  0.4539],
        [-0.0262, -0.0413, -0.0363]]) torch.Size([5, 3])


In [18]:
y = x / torch.sqrt(torch.randn(5, 3) ** 2)
print(y, y.shape)

tensor([[ 1.4377e-01, -6.1878e-01,  7.3342e-03],
        [ 2.7690e+00,  1.7429e+00, -1.0810e+01],
        [-1.4265e-01,  1.9323e+00, -7.1310e-01],
        [-5.0678e-01,  2.1320e-01,  6.4995e-01],
        [ 4.2306e-01, -1.2846e-01, -6.4339e-01]]) torch.Size([5, 3])


### Broadcasting

Broadcasting semantics - https://pytorch.org/docs/stable/notes/broadcasting.html

In [25]:
print(x.shape)
y = torch.randn(5, 3) + torch.randn(3,)
print(y, y.shape)

torch.Size([5, 3])
tensor([[ 0.5830,  0.6702,  1.7704],
        [ 0.8219, -3.0025,  0.7334],
        [ 0.8698, -1.5706,  0.6873],
        [ 1.5344, -1.6093, -0.1483],
        [-0.2521, -0.6823, -0.2108]]) torch.Size([5, 3])


### Reshape

In [27]:
y = torch.randn(5, 10, 15)
print(y.size())
print(y.view(-1, 15).shape)  # Same as doing y.view(50, 15)
print(y.view(-1, 15).unsqueeze(1).shape) # Adds a dimension at index 1.
print(y.view(-1, 15).unsqueeze(1).squeeze().shape)
# Squeeze - If input is of shape: (Ax1xBxCx1xD) then the out Tensor will be of shape: (AxBxCxD)
print()
print(y.transpose(0, 1).size())
print(y.transpose(1, 2).size())
print(y.transpose(0, 1).transpose(1, 2).size())
print(y.permute(1, 2, 0).size())

torch.Size([5, 10, 15])
torch.Size([50, 15])
torch.Size([50, 1, 15])
torch.Size([50, 15])

torch.Size([10, 5, 15])
torch.Size([5, 15, 10])
torch.Size([10, 15, 5])
torch.Size([10, 15, 5])


### Repeat

In [28]:
print(y.view(-1, 15).unsqueeze(1).expand(50, 100, 15).size())
print(y.view(-1, 15).unsqueeze(1).expand_as(torch.randn(50, 100, 15)).size())

torch.Size([50, 100, 15])
torch.Size([50, 100, 15])


### Concatenate

In [29]:
# 2 is the dimension over which the tensors are concatenated
print(torch.cat([y, y], 2).size())
# stack concatenates the sequence of tensors along a new dimension.
print(torch.stack([y, y], 0).size())

torch.Size([5, 10, 30])
torch.Size([2, 5, 10, 15])


### Advanced Indexing

In [30]:
y = torch.randn(2, 3, 4)
print(y[[1, 0, 1, 1]].size())

# PyTorch doesn't support negative strides yet so ::-1 does not work.
rev_idx = torch.arange(1, -1, -1).long()
print(y[rev_idx].size())

torch.Size([4, 3, 4])
torch.Size([2, 3, 4])


### GPU support

In [31]:
x = torch.cuda.HalfTensor(5, 3).uniform_(-1, 1)
y = torch.cuda.HalfTensor(3, 5).uniform_(-1, 1)
torch.matmul(x, y)

AssertionError: Torch not compiled with CUDA enabled

### Move tensors on the CPU -> GPU

In [32]:
x = torch.FloatTensor(5, 3).uniform_(-1, 1)
print(x)
x = x.cuda(device=0)
print(x)
x = x.cpu()
print(x)

tensor([[ 0.7883, -0.7699, -0.1115],
        [ 0.5383,  0.8297,  0.0285],
        [ 0.9291,  0.9964,  0.6803],
        [-0.5468, -0.2749,  0.9764],
        [-0.7262, -0.0451, -0.4922]])


AssertionError: Torch not compiled with CUDA enabled

### Contiguity in memory

In [33]:
x = torch.FloatTensor(5, 3).uniform_(-1, 1)
print(x)
x = x.cuda(device=0)
print(x)
print('Contiguity : %s ' % (x.is_contiguous()))
x = x.unsqueeze(0).expand(30, 5, 3)
print('Contiguity : %s ' % (x.is_contiguous()))
x = x.contiguous()
print('Contiguity : %s ' % (x.is_contiguous()))

tensor([[ 0.9719, -0.6959,  0.9101],
        [ 0.8057,  0.9393, -0.5073],
        [ 0.5429,  0.2452,  0.6467],
        [ 0.4303,  0.8575, -0.9592],
        [-0.3579, -0.4061, -0.5224]])


AssertionError: Torch not compiled with CUDA enabled